### ISSUE TITLE
第三章中的 3.1.2组件平台自适应，需要新建哪些文件

### ISSUE THREAD

**Issue by ChenYCL** [es6rn/Readme-first#12]
55页中，建立文件改名，但是第二页中导入的 LoginLeaf  WaitingLeaf完全在前方没有建立，前面只是建立的
LoginLeaf.android.js和备份文件LoginLeaf.ios.js, 还有RegisterLeaf.ios.js前方也没出现过！！！，然后直接就说TextInput组件样式设置，到这里完全不知道作者想表达什么了

**Comment by changliugang** [comment]
“55页中，建立文件改名，但是第二页中导入的 LoginLeaf WaitingLeaf完全在前方没有建立”
关于这个呢，你看到3.2的最后一段就知道了，作者是用的后面的代码作为示例的。不必较真。
‘’前面只是建立的
LoginLeaf.android.js和备份文件LoginLeaf.ios.js, 还有RegisterLeaf.ios.js前方也没出现过！！！‘’
关于这句呢，又是一句笔误，第一版印刷小问题还是有的，体谅下作者呗
