### ISSUE TITLE
第七章的日记demo

### ISSUE THREAD

**Issue by changliugang** [es6rn/Readme-first#13]
大神，这个demo的小bug不少，你要不还是自己敲一遍运行下看看吧

**Comment by es6rn** [comment]
书中所有的例程，在RN 0.42版本中都运行通过了的......

**Comment by es6rn** [comment]
我在RN 0.47上建了个工程，然后把书中的代码一字不改的copy了进去，然后运行，没有任何问题。
请问你说的bug是怎样发生的？
