### ISSUE TITLE
（第一次印刷 page147） 第 6.1.2 章的关于 ellipsizeMode

### ISSUE THREAD

**Issue by 164738777** [es6rn/Readme-first#14]
[Text 组件](http://facebook.github.io/react-native/docs/text.html)

文档中提到， clip 只支持iOS。

其他三个属性在 Android 6.0.1 亲测，都是可以的。

书中，147页的最后一行，却是写，`但截至 RN 0.40 ，只有iOS平台支持了前三种属性。在Android平台，所有取值效果都与clip属性相同`。

可能后面版本改了吧。

**Comment by es6rn** [comment]
对
