### ISSUE TITLE
（第一次印刷 page157-158、165） 第 6.2.5、6.4.6 章的关于 text 、textInput 加边框在两个平台的不同表现问题

### ISSUE THREAD

**Issue by 164738777** [es6rn/Readme-first#16]
亲测，Android 6.0.1 用 Text 组件 直接在 style 里面加上 `borderWidth: 1` 就会出现边框，并不需要再嵌套一层 View 。

**Comment by 164738777** [comment]
同理，**Page 165** 的` TextInput 的 borderWidth: 1`  也是亲测有效。

**Comment by es6rn** [comment]
原来版本存在着问题，新版本改进了。
