### ISSUE TITLE
在"Readme-first-master"文件夹的"第三章更新"中提到如何使用旧的Navigator组件有疑问

### ISSUE THREAD

**Issue by lunzhenmin** [es6rn/Readme-first#17]
文档是这样说的: 
从RN 0.44开始，RN官方从RN中删除了Navigator组件。如果在原来的RN应用中使用了这个组件，还希望使用这个组件，可以先在窗口模式下，进入项目目录运行：
        npm install --save react-native-deprecated-custom-components
然后在项目中这样导入Navigator组件：
import {
     Navigator  
} from 'react-native-deprecated-custom-components';

但是我按照上面方法安装导入后项目运行不起来, 不知道为什么, 安装组件后发现好像被删了好多东西

**Comment by es6rn** [comment]
因为Navigator组件很久前就不再维护，它与最新版本的RN能否配合使用也就没有资料了。请使用本github上提供的最新第三章与第十章文档学习。如果实在要使用Navigator组件，建议是创建0.43版本之前的RN项目，在那下面学习。
