### ISSUE TITLE
关于 FlatList 和 SectionList 的内容

### ISSUE THREAD

**Issue by charleylla** [es6rn/Readme-first#18]
作者你好，第八章中写到了 ScrollView 和 ListView 的内容，我在 React Native 中文网上看到，现版本已经不推荐使用 ListView 了，推荐使用 FlatList 和 SectionList。有时间的话可以更新下这部分内容

**Comment by es6rn** [comment]
谢谢你的提醒，将在下一版中加入相关内容。
