### ISSUE TITLE
关于index.android.js和index.ios.js

### ISSUE THREAD

**Issue by aoarashi1988** [es6rn/Readme-first#20]
看了你的书，包括在github更新的时候，依然在使用index.XXX.js的叙述方式，这对初学者可能会造成困扰，因为现在RN的启动默认页面已经统一变为了App.js了，希望能在下次更新的时候更正。

**Comment by aoarashi1988** [comment]
代码5-2-5，pointerEvent属性写在了Text组件上，点击small button并不会让big button失效，需要用一个View组件包裹big button，然后改变这个View的pointerEvent才可以

**Comment by es6rn** [comment]
你好，你说的index.XXXX.js的问题，已经更新在第二章更新中了。谢谢你的帮助。
