### ISSUE TITLE
Apple 封杀热更新对React Native在iOS上的使用有影响吗?

### ISSUE THREAD

**Issue by csdwd** [es6rn/Readme-first#3]
Apple 封杀热更新对React Native 有影响吗?
React Native的热更新 在iOS上还能用吗? 能否正常上线

**Comment by CodingMonkeyzh** [comment]
see: http://blog.cnbang.net/internet/3374/

**Comment by es6rn** [comment]
我在书中已经写了，目前还没有听到对CodePush方案有影响。
