### ISSUE TITLE
第五章 使用导航栏的导航框架代码跑不通

### ISSUE THREAD

**Issue by yufengkz** [es6rn/Readme-first#4]
请问这是为什么呢？是和第二章一样用了react-native中移除的Navigator吗？那要怎么才能跑起来啊？

**Comment by es6rn** [comment]
对，是因为使用了Navigator，如果你按我第三章更新中说的方法把Navigator组件加载起来就可以跑起来。但不建议学习这个。第十章更新的pdf文件中有新的使用导航栏导航的例子。将来都用它了。

**Comment by yufengkz** [comment]
好的，谢谢，我按照第二章的单独引进来也不能运行，我直接用新的试试去。
