### ISSUE TITLE
11.4.3 单点手势 代码11-4-4

### ISSUE THREAD

**Issue by WeiXiangLuo** [es6rn/Readme-first#5]
在书本的275-276页
在LearnRN类的constructor方法中，有这样一句代码
this.startX = 0;
请问这是什么？既不是属性也不是状态？还是说是静态变量嘛？
这个变量无法在该例子的_onPanResponderGrant方法中改变其值？
请问如何解决

**Comment by es6rn** [comment]
这是JS对象的成员变量，关于它的说明参见本书2.8.
它的值在_onPanResponderGrant中应当是可以改变的。
书中的例程都在RN 0.42版本中运行过的。
你再仔细检查下你的代码？
