### ISSUE TITLE
(第一次印刷)5.2.7 pointerEvents属性

### ISSUE THREAD

**Issue by changliugang** [es6rn/Readme-first#7]
(第一次印刷 page124)5.2.7 pointerEvents属性 示例代码5-2-5 代码运行效果和下面的描述不符。使用简书作者 于连林520wcf （http://www.jianshu.com/p/70773038d850）的代码做出书中描述的效果。

和他同问一下，“本来大按钮并没有单独用一个View组件嵌套, 直接把pointerEvent属性定义在大按钮的Text组件上, 在Android设备上发现没有效果, 有点不明觉厉了, 不知道是RN的Bug还是Android就是这种机制, 请大神解答了”

**Comment by 164738777** [comment]
+1，按照书上的代码，根本不会屏蔽大button的点击事件啊。。。

**Comment by 164738777** [comment]
render 里面需要这么写才有用，其他代码不需要改，styles里面也改下相应的。
也就是需要在 Big Button 那个Text 的外层加个View，将pointerEvents属性放在View那里；
如果放在 Big Button 那个Text 那里，会无效。
```
render() {
        return (
            <View style={styles.container}>
                <Text style={styles.abtn}
                      onPress={this.onSmallButtonPressed}>Small Button</Text>
                <View style={styles.bbtn}
                      pointerEvents={this.state.bigButtonPointerEvents}>
                    <Text style={{flex: 1, fontSize: 20}}
                          onPress={this.onBigButtonPressed}>Big Button</Text>
                </View>
            </View>
        );
    }
```
