### ISSUE TITLE
（第一次印刷 page126）代码5-3-2

### ISSUE THREAD

**Issue by changliugang** [es6rn/Readme-first#8]
![image](https://user-images.githubusercontent.com/8650656/28516695-acf772fa-7094-11e7-9bc8-e138696a861d.png)

我是萌新小白，这里不知道是怎么回事，哪里写错了请指教

**Comment by es6rn** [comment]
因为RN代码在不断变动之中，如果promise方式得不到宽高，就用原来的吧。
