### ISSUE TITLE
（第一次印刷page177）代码6-9-1高度自增长的扩展TextInput组件

### ISSUE THREAD

**Issue by changliugang** [es6rn/Readme-first#9]
输入文字出发onChang报错
undefined is not an object(evaluating 'event.nativeEvent.contentSize.height')
求解

**Comment by es6rn** [comment]
从RN 0.46开始，在onChage属性的回调中不再携带contentSize。如果需要获取contentSize，新版RN提供了onContentSizeChange回调属性。但在RN 0.47.1环境中调用onContentSizeChange，无法正确获取到高度。我已经向RN社区反映了这个问题。目前只能等待这个bug的修复。
